package br.com.bruno.cadastro.domain;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;


@DynamoDBTable(tableName = "Delivery")
@Data
@NoArgsConstructor
@Builder
@AllArgsConstructor
public class DeliveryEntity {


    @DynamoDBHashKey()
    @DynamoDBAutoGeneratedKey
    String idDelivery;
    AddressEntity address;
    String nameUser;
    InfoUsersEntity infoUsers;
    String idUser;
    String create_at;
    String update_at;
}
