package br.com.bruno.cadastro.domain;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;


@DynamoDBTable(tableName = "Users")
@Data
@NoArgsConstructor
@Builder
@AllArgsConstructor
public class UsersEntity {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    String id;
    String name;
    Integer age;
    DeliveryMouthEntity month;
    Boolean stats;
    Boolean mainParent;
    String idMainParent;
    InfoUsersEntity infoUsers;
    AddressEntity address;
    String create_at;
    String update_at;

}
